config/routes.rb
HowToBeAlone::Application.routes.draw do

    resources :meditations
    resources :feelings

end

app/models/feeling.rb
class Feeling < ActiveRecord::Base
end

app/models/meditation.rb
class Meditation < ActiveRecord::Base
	has_many :feelings

	def before_feeling
	end

	def after_feeling
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feelings_controller.rb
class FeelingsController < ApplicationController
	respond_to :html

	skip_before_filter  :verify_authenticity_token

	def create
		respond_to do |format|
			format.html { render :json => Feeling.create(feeling_params) }
		end
	end

	private
	def feeling_params
      params.require(:feeling).permit(:feeling_desc)
    end
end

app/controllers/meditations_controller.rb
class MeditationsController < ApplicationController
	respond_to :html

	skip_before_filter  :verify_authenticity_token

	def create
		respond_to do |format|
			format.html { render :json => Meditation.create(meditation_params) }
		end
	end

	def index
	    respond_to do |format|
	      format.html { render json: Meditation.all }
	      format.json { render json: Meditation.all }
	    end
	end

    private

	def meditation_params
      params.require(:meditation).permit(:duration, :thoughts)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="htbaApp">
<head>
  <title>HowToBeAlone</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <!-- Include all compiled plugins (below), or include individual files as needed -->

<%= yield %>

</body>
</html>

app/views/meditations/dashboard.html.erb
 <div id="dashboard">
<div id="dash_button">
<%= button_to "Meditate", meditations_path, id: "med",class: "btn btn-lg btn-default", method: "get" %>

<%= button_to "View History", meditations_path, id: "view",class: "btn btn-lg btn-default", method: "get" %>
</div>

      </div>

app/views/meditations/index.html.erb
<div class='span5' id="home_page" ng-controller="FeelingsCtrl">
	<h1> {{heading}} </h1>
	<h2> <%= link_to "How do you feel now?", "#", class: "todays-emotion" %> </h2>
  <div id="emotion_button">
  	<span ng-repeat="f in feelings">
       <button ng-click="selectFeeling(f)" class="btn btn-lg btn-primary">{{f.name}}</button>
     </span>
  </div>
</div>